DFlesh/urls.py
from django.conf.urls import include, url
from django.contrib import admin
#from df_goods import search_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/',include('df_user.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^goods/',include('df_goods.urls')),
    url(r'^order/', include('df_order.urls')),
    url(r'^cart/', include('df_cart.urls')),
    #url(r'^search/', search_views.MySeachView(), name='haystack_search'),
]

df_user/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register/$',views.register),
    url(r'^register_handle/$',views.register_handle),
    url(r'^register_exist/$',views.register_exist),
    url(r'^login/$',views.login),
    url(r'^login_handle/$',views.login_handle),
    #url(r'^index/$',views.index),
    url(r'^info/$',views.info),
    url(r'^order/$',views.order),
    url(r'^site/$',views.site),
    url(r'^logout/$',views.logout),
    url(r'^user_center_order&(\d+)/$', views.user_center_order),
]

df_order/models.py
from django.db import models

# Create your models here.
class OrderInfo(models.Model):
    oid = models.CharField(max_length=20,primary_key=True)
    user = models.ForeignKey('df_user.UserInfo',on_delete=models.CASCADE)
    odate = models.DateTimeField(auto_now=True)
    oIsPay = models.IntegerField(default=0)
    ototal = models.DecimalField(max_digits=6,decimal_places=2)
    oaddress = models.CharField(max_length=150,default='')
    zhifu = models.IntegerField(default=0)

class OrderDetailInfo(models.Model):
    goods=models.ForeignKey('df_goods.GoodInfo',on_delete=models.CASCADE)
    order=models.ForeignKey(OrderInfo,on_delete=models.CASCADE)
    price=models.DecimalField(max_digits=5,decimal_places=2)
    count=models.IntegerField()

df_user/models.py
from django.db import models

# Create your models here.
class UserInfo(models.Model):
    uname = models.CharField(max_length=20)
    upwd = models.CharField(max_length=40)
    uemail = models.CharField(max_length=30)
    ureceiver = models.CharField(max_length=20,default='')
    uaddress = models.CharField(max_length=100,default='')
    upostcode = models.CharField(max_length=6,default='')
    uphone = models.CharField(max_length=11,default='')

df_user/views.py
from django.shortcuts import render,redirect,HttpResponseRedirect
from hashlib import sha1
from .models import *
from django.http import JsonResponse
from .islogin import islogin
from df_goods.models import GoodInfo
from df_order.models import OrderInfo
from django.core.paginator import Paginator
from df_cart.models import *

# Create your views here.
def register(request):
    context = {'title':'用户注册'}
    return render(request,'df_user/register.html',context)

def register_handle(request):
    #接收输入
    post = request.POST
    uname = post.get('user_name')
    upwd = post.get('pwd')
    upwd2 = post.get('cpwd')
    uemail = post.get('email')
    #判断两次密码
    if upwd!=upwd2:
        return redirect('/user/register/')
    #密码加密
    s1 = sha1()
    s1.update(upwd.encode('utf-8'))
    upwd3 = s1.hexdigest()
    #创建对象，存储数据
    user = UserInfo()
    user.uname = uname
    user.upwd = upwd3
    user.uemail = uemail
    user.save()
    #注册成功转到登录页
    return redirect('/user/login/')

def register_exist(request):
    uname = request.GET.get('uname')
    count = UserInfo.objects.filter(uname=uname).count()#只需要判断存不存在记个数就可以了
    return JsonResponse({'count':count})#思考什么时候是返回一个json数据呢

def login(request):
    uname = request.COOKIES.get('uname','')
    context = {'title':'用户登录','error_name':0,'error_pwd':0,'uname':uname}
    return render(request,'df_user/login.html',context)#context: 要传入文件中用于渲染呈现的数据, 默认是字典格式

def login_handle(request):
    #接收请求信息
    post = request.POST
    uname = post.get('username')
    upwd = post.get('pwd')
    remember = post.get('remember',0)
    #根据用户名查询对象
    user = UserInfo.objects.filter(uname=uname)
    #如果能查到正确的用户名，则判断密码是否正确，都正确则转向用户中心
    if len(user)==1:
        s1 = sha1()
        s1.update(upwd.encode('utf-8'))
        upwd = s1.hexdigest()

        if upwd==user[0].upwd:
            red = HttpResponseRedirect('/goods/index/')
            count = CartInfo.objects.filter(user_id=user[0].id).count()

            #记住用户名
            if remember != 0:
                red.set_cookie('uname',uname)
            else:
                red.set_cookie('uname','',max_age=-1)
            request.session['user_id'] = user[0].id
            request.session['user_name'] = uname
            request.session['count'] = count
            return red
        else:
            context = {'title':'用户登录','error_name':0,'error_pwd':1,'uname':uname}
            return render(request,'df_user/login.html',context)
    else:
        context = {'title': '用户登录', 'error_name': 1, 'error_pwd': 0, 'uname': uname}
        return render(request, 'df_user/login.html', context)


#def index(request):
#    context = {'title':'首页'}
#    return render(request,'df_goods/index.html',context)

# 登录用户中心
@islogin
def info(request):
    user_email = UserInfo.objects.get(id=request.session['user_id']).uemail
    user_phone = UserInfo.objects.get(id=request.session['user_id']).uphone
    user_address = UserInfo.objects.get(id=request.session['user_id']).uaddress
#此处应有最近浏览代码
    # 最近浏览
    good_ids = request.COOKIES.get('good_ids', '')
    good_id_list = good_ids.split(',')
    good_list = []
    if len(good_ids):
        for goods_id in good_id_list:
            good_list.append(GoodInfo.objects.get(id=int(goods_id)))

    context = {'title': '用户中心',
               'user_email': user_email,
               'user_name': request.session['user_name'],
               'page_name':1,'info':1,
               'user_phone':user_phone,
               'user_address':user_address,
               'good_list': good_list,
               }
    return render(request, 'df_user/user_center_info.html', context)

#我的订单
@islogin
def order(request):
    context = {'title':'用户中心','page_name':1,'order':1}
    return render(request,'df_user/user_center_order.html',context)

#收货地址
@islogin
def site(request):
    user = UserInfo.objects.get(id=request.session['user_id'])
    if request.method == 'POST':
        post = request.POST
        user.ureceiver = post.get('ureceiver')
        user.uaddress = post.get('uaddress')
        user.uphone = post.get('uphone')
        user.upostcode = post.get('upostcode')
        user.save()
    context = {'title':'用户中心','user':user,'page_name':1,'site':1}
    return render(request,'df_user/user_center_site.html',context)

def logout(request):
    request.session.flush()
    return redirect('/goods/index/')

@islogin
def user_center_order(request, pageid):
    """
    此页面用户展示用户提交的订单，由购物车页面下单后转调过来，也可以从个人信息页面查看
    根据用户订单是否支付、下单顺序进行排序
    """

    uid = request.session.get('user_id')
    # 订单信息，根据是否支付、下单顺序进行排序
    orderinfos = OrderInfo.objects.filter(
        user_id=uid).order_by('zhifu', '-oid')

    # 分页
    #获取orderinfos list  以两个为一页的 list
    paginator = Paginator(orderinfos, 2)
    # 获取 上面集合的第 pageid 个 值
    orderlist = paginator.page(int(pageid))
    #获取一共多少 页
    plist = paginator.page_range
    #3页分页显示
    qian1 = 0
    hou = 0
    hou2 = 0
    qian2 = 0
    # dd = dangqian ye
    dd = int(pageid)
    lenn = len(plist)
    if dd>1:
        qian1 = dd-1
    if dd>=3:
        qian2 = dd-2
    if dd<lenn:
        hou = dd+1
    if dd+2<=lenn:
        hou2 = dd+2



    # 构造上下文
    context = {'page_name': 1, 'title': '全部订单', 'pageid': int(pageid),
               'order': 1, 'orderlist': orderlist, 'plist': plist,
               'pre':qian1,'next':hou,'pree':qian2,'lenn':lenn,'nextt':hou2}

    return render(request, 'df_user/user_center_order.html', context)

templates/df_user/index.html
{% extends 'base.html' %}

{% block head %}
<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="/static/js/slide.js"></script>
{#<script type="text/javascript" src="/static/js/slideshow.js"></script>#}
	<script type="text/javascript">
{#		BCSlideshow('focuspic');#}
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(d){
			window.location.href = 'list.html';
		}
	</script>
{% endblock head %}

{% block body %}

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="/goods/index/">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model03" class="meet">猪牛羊肉</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg"></a>
			<a href="#"><img src="/static/images/adv02.jpg"></a>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">新鲜水果</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for g in fruit_click %}
				<a href="/goods/{{g.id}}">{{g.good_title|slice:'10'}}</a>
				{% endfor %}
			</div>
			<a href="/goods/list1_1_1/" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner01.jpg"></div>
			<ul class="goods_list fl">
				{% for g in fruit %}
				<li>
					<h4><a href="/goods/{{g.id}}">{{g.good_title|slice:'10'}}</a></h4>
					<a href="/goods/{{g.id}}"><img src="/static/{{g.good_image}}"></a>
					<div class="prize">¥ {{g.good_price}}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model02">海鲜水产</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for g in seafood_click %}
				<a href="/goods/{{g.id}}">{{g.good_title|slice:'10'}}</a>
				{% endfor %}
			</div>
			<a href="/goods/list2_1_1/" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner02.jpg"></div>
			<ul class="goods_list fl">
				{% for g in seafood %}
				<li>
					<h4><a href="/goods/{{g.id}}">{{g.good_title|slice:'10'}}</a></h4>
					<a href="/goods/{{g.id}}"><img src="/static/{{g.good_image}}"></a>
					<div class="prize">¥{{g.good_price}}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model03">猪牛羊肉</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for g in meat %}
				<a href="/goods/{{g.id}}">{{g.good_title|slice:'10'}}</a>
				{% endfor %}
			</div>
			<a href="/goods/list3_1_1/" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner03.jpg"></div>
			<ul class="goods_list fl">
				{% for g in meat_click %}
				<li>
					<h4><a href="/goods/{{g.id}}">{{g.good_title|slice:'10'}}</a></h4>
					<a href="/goods/{{g.id}}"><img src="/static/{{g.good_image}}"></a>
					<div class="prize">¥{{g.good_price}}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model04">禽类蛋品</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for g in egg %}
				<a href="/goods/{{g.id}}">{{g.good_title|slice:'10'}}</a>
				{% endfor %}
			</div>
			<a href="/goods/list4_1_1/" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner04.jpg"></div>
			<ul class="goods_list fl">
				{% for g in egg_click %}
				<li>
					<h4><a href="/goods/{{g.id}}">{{g.good_title|slice:'10'}}</a></h4>
					<a href="/goods/{{g.id}}"><img src="/static/{{g.good_image}}"></a>
					<div class="prize">¥{{g.good_price}}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model05">新鲜蔬菜</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for g in vegetable %}
				<a href="/goods/{{g.id}}">{{g.good_title|slice:'10'}}</a>
				{% endfor %}
			</div>
			<a href="/goods/list5_1_1/" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner05.jpg"></div>
			<ul class="goods_list fl">
				{% for g in vegetable_click %}
				<li>
					<h4><a href="/goods/{{g.id}}">{{g.good_title|slice:'10'}}</a></h4>
					<a href="/goods/{{g.id}}"><img src="/static/{{g.good_image}}"></a>
					<div class="prize">¥{{g.good_price}}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model06">速冻食品</h3>
			<div class="subtitle fl">
				<span>|</span>
				{% for g in freezefood %}
				<a href="/goods/{{g.id}}">{{g.good_title|slice:'10'}}</a>
				{% endfor %}
			</div>
			<a href="/goods/list6_1_1/" class="goods_more fr">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner06.jpg"></div>
			<ul class="goods_list fl">
				{% for g in freezefood_click %}
				<li>
					<h4><a href="/goods/{{g.id}}">{{g.good_title|slice:'10'}}</a></h4>
					<a href="/goods/{{g.id}}"><img src="/static/{{g.good_image}}"></a>
					<div class="prize">¥{{g.good_price}}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

{% endblock body %}

templates/df_user/login.html
{% extends 'base_bottom.html' %}

{% block head %}
<script>
	$(function () {
		name_error = false
		pwd_error = false
		if($('.name_input').val().length!=0){
			name_error = true
		}
		if($('.pwd_error').val().length!=0){
			pwd_error = true
		}

		if({{ error_name }}==1){
			$('.user_error').html('用户名错误').show();
		}
		if({{ error_pwd }}==1){
			$('.pwd_error').html('密码错误').show();
		}

		$('.name_input').blur(function () {
			if($('.name_input').val().length==0){
				$('.user_error').html('请填写用户名').show();
				name_error = false;
			}else{
				$('.user_error').hide();
				name_error = true;
			}
		})

		$('.pass_input').blur(function () {
			if($('.pass_input').val().length==0){
				$('.pwd_error').html('请填写密码').show();
				pwd_error = false;
			}else{
				$('.pwd_error').html().hide();
				pwd_error =true;
			}
		})

		$(":submit[id=lo]").click(function (check) {
			console.log(pwd_error,name_error)
			if(pwd_error==false||name_error==false){
				check.prventDefault();
			}
		});
	})
</script>
{% endblock head %}

{% block body %}
	<div class="login_top clearfix">
		<a href="/goods/index/" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form id="form" action="/user/login_handle/" method="post">
						{% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" value="1">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input id="lo" type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock body%}

templates/df_user/register.html
{% extends 'base_bottom.html' %}

{% block head %}
<script type="text/javascript" src="/static/js/register.js"></script>
{% endblock head %}

{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="/user/register_handle/" id="reg_form" method="post">
					{% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>
				</form>
			</div>

		</div>

	</div>
{% endblock body %}

templates/df_user/user_center_info.html
{% extends 'base.html' %}


{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/" class="active">· 个人信息</a></li>
				<li><a href="/user/user_center_order&1/">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{user_name}}</li>
							<li><span>联系方式：</span>{{user_phone}}</li>
							<li><span>联系地址：</span>{{user_address}}</li>
						</ul>
				</div>

				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
					{% for good in good_list %}
					<li>
						<a href="/goods/{{good.id}}"><img src="/static/{{good.good_image}}"></a>
						<h4><a href="/goods/detail/">{{good.good_title}}</a></h4>
						<div class="operate">
							<span class="prize">￥{{good.good_price}}</span>
							<span class="unit">{{good.good_price}}/{{good.good_unit}}</span>
							<a href="#" class="add_goods" title="加入购物车"></a>
						</div>
					</li>
					{% endfor %}
					</ul>
				</div>
		</div>
	</div>
{% endblock body %}

templates/df_user/user_center_order.html
{% extends 'base.html' %}

{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/user_center_order&1/" class="active">· 全部订单</a></li>
				<li><a href="/user/site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				{% for orderinfo in orderlist %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{orderinfo.odate}}</li>
					<li class="col02">订单号：{{orderinfo.oid}}</li>
					{% if orderinfo.zhifu == 1 %}
        			<li class="col02 stress">已支付</li>
        			{% else %}
        			<li class="col02 stress">未支付</li>
        			{% endif %}
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								{% for item in orderinfo.orderdetailinfo_set.all %}
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="/static/{{item.goods.good_image}}"></li>
									<li class="col02">{{item.goods.good_title}}<em>{{item.goods.good_price}}<span>{{item.price}}</span>元/{{item.goods.good_unit}}</em></li>
									<li class="col03">{{item.count}}</li>
									<li class="col04"></li>
								</ul>
								{% endfor %}
							</td>
							<td width="15%">{{orderinfo.ototal}}元</td>
							{% if orderinfo.zhifu == 1 %}
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
							{% else %}
							<td width="15%">未付款</td>
							<td width="15%"><a href="/order/pay&{{orderinfo.oid}}/" class="oper_btn">去付款</a></td>
							{% endif %}
					</tr>
					</tbody>
				</table>
				{% endfor %}

				<div class="pagenation">
					{% if orderlist.has_previous %}
					<a href="/user/user_center_order&{{orderlist.previous_page_number}}/">
						上一页
					</a>
					{% endif %}
			{#    分页 ： plist 一共多少页  pageid 当前页  orderlist paginator按照两个一页，分的，页的指向对象  #}
				{% if lenn < 4  %}
					{% if lenn == 1 %}
						<a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
					{% elif lenn == 2 %}
						{% if pageid == 1 %}
						<a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
						<a href="/user/user_center_order&{{next}}/" >{{next}}</a>
						{% else %}
						<a href="/user/user_center_order&{{pre}}/" >{{pre}}</a>
						<a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
						{% endif %}
					{% elif lenn == 3%}

						{% if pageid == 1 %}
						<a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
						<a href="/user/user_center_order&{{next}}/" >{{next}}</a>
						<a href="/user/user_center_order&{{nextt}}/" >{{nextt}}</a>
						{% elif pageid == 2 %}
						<a href="/user/user_center_order&{{pre}}/" >{{pre}}</a>
						<a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
						<a href="/user/user_center_order&{{next}}/" >{{next}}</a>
						{% else %}
						<a href="/user/user_center_order&{{pree}}/" >{{pree}}</a>
						<a href="/user/user_center_order&{{pre}}/" >{{pre}}</a>
						<a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
						{% endif %}
					{% endif %}
				{% elif pageid < lenn %}
					{% if orderlist.has_previous  %}
					<a href="/user/user_center_order&{{pre}}/" >{{pre}}</a>
					<a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
					<a href="/user/user_center_order&{{next}}/" >{{next}}</a>
					{% else %}
					<a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
					<a href="/user/user_center_order&{{next}}/" >{{next}}</a>
					<a href="/user/user_center_order&{{nextt}}/" >{{nextt}}</a>
					{% endif %}
				{% else %}
					<a href="/user/user_center_order&{{pree}}/" >{{pree}}</a>
					<a href="/user/user_center_order&{{pre}}/" >{{pre}}</a>
					<a href="/user/user_center_order&{{pageid}}/" class="active">{{pageid}}</a>
				{% endif %}


					{% if orderlist.has_next %}
					<a href="/user/user_center_order&{{orderlist.next_page_number}}/">下一页></a>
					{% endif %}
				</div>
			</div>
		</div>
{% endblock body %}

templates/df_user/user_center_site.html
{% extends 'base.html' %}

{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/info/">· 个人信息</a></li>
				<li><a href="/user/user_center_order&1/">· 全部订单</a></li>
				<li><a href="/user/site/" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{user.uaddress}} （{{user.ureceiver}} 收） 电话：{{user.uphone}} 邮编：{{user.upostcode}}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="/user/site/" method="post">
						{% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="ureceiver" value="{{user.ureceiver}}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="uaddress">{{user.uaddress}}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="upostcode" value="{{user.upostcode}}">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="uphone" value="{{user.uphone}}">
						</div>

						<input type="submit" name="" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>

{% endblock body %}